### PR TITLE
added serial communication to control PTT on HT

### PR DESCRIPTION
**Pull request by kyleparrott**
I have an Arduino with a relay hooked up to my handy talky controlling the PTT. This programmatically pushes and releases the PTT button for us.

### CODE REVIEW

**Comment by NickTompkins123** [comment]
Wooohoo

**Comment by marshall** [comment]
:heart: @kyleparrott

**Comment by marshall** [comment]
Can you add a unit test that mocks the output of your arduino? Also, do you have the code for the relay somewhere that we can add to this repository?

**Comment by marshall** [comment]
Ignore my comment about unit tests, just saw your comment in slack :)

**Pull request merged**
